insert into smer(oznaka, naziv, datum, opis) values ('siit', 'softversko inzenjerstvo i informacione tehnologije', '10.10.2014','opis smera' )
insert into predmet(oznaka, naziv, opis, smer_oznaka, velicina_grupe, duzina_termina, broj_termina, projektor, tabla, pametna_tabla, op_sistem  ) values ('HCI', 'Interakcija covek racunar', 'opis predmeta', 'siit', '15', '2', '4', true, true, false, 'LINUX' )
insert into predmet(oznaka, naziv, opis, smer_oznaka, velicina_grupe, duzina_termina, broj_termina, projektor, tabla, pametna_tabla, op_sistem  ) values ('ISA', 'Baze podataka', 'opis predmeta', 'siit', '15', '3', '4', true, true, false, 'LINUX' )
insert into predmet(oznaka, naziv, opis, smer_oznaka, velicina_grupe, duzina_termina, broj_termina, projektor, tabla, pametna_tabla, op_sistem  ) values ('MRS', 'Baze podataka', 'opis predmeta', 'siit', '15', '4', '4', true, true, false, 'WINDOWS' )

insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L1', 'opis ucionice', '25', false, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L2', 'opis ucionice', '10', true, true, true, 'LINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L3', 'opis ucionice', '25', true, true, true, 'WINDOWS')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L17', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L4', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L5', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L6', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L7', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L8', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L9', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L10', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L11', 'opis ucionice', '25', true, true, true, 'WINLINUX')

insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('VS15', 'Visual studio', 'Microsoft', 'www.microsoft.com', '2015', 'opis proizvoda', '2000')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('MTLB13', 'MATLAB R2013', 'MathWorks', 'www.mathworks.com', '2013', 'Matlab softver', '500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('PYCH', 'PyCharm 2015', 'JetBrains', 'www.jetbrains.com', '2015', 'Python IDE', '1500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('ECL', 'Eclipse Neon', 'Eclipse Foundation', 'www.eclipse.org', '2017', 'Eclipse IDE', '1700')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('AAA13', 'MATLABAA R2013', 'MathWorks', 'www.mathworks.com', '2013', 'Matlab softver', '500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('BBB13', 'PyCharmBB 2015', 'JetBrains', 'www.jetbrains.com', '2015', 'Python IDE', '1500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('ECL13', 'Eclipse13 Neon', 'Eclipse Foundation', 'www.eclipse.org', '2017', 'Eclipse IDE', '1700')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('MTLB213', 'MATLAehB R2013', 'MathWorks', 'www.mathworks.com', '2013', 'Matlab softver', '500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('PYCHg', 'asdasd 2015', 'JetBrains', 'www.jetbrains.com', '2015', 'Python IDE', '1500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('ECaL', 'WWW Neon', 'Eclipse Foundation', 'www.eclipse.org', '2017', 'Eclipse IDE', '1700')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('MTLbB13', 'MbBDAB R2013', 'MathWorks', 'www.mathworks.com', '2013', 'Matlab softver', '500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('PYCHy', 'fQWFarm 2015', 'JetBrains', 'www.jetbrains.com', '2015', 'Python IDE', '1500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('ECcL', 'QDHDHNeon', 'Eclipse Foundation', 'www.eclipse.org', '2017', 'Eclipse IDE', '1700')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('MTjLB13', 'dhehB R2013', 'MathWorks', 'www.mathworks.com', '2013', 'Matlab softver', '500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('PtrYCH', 'xch015', 'JetBrains', 'www.jetbrains.com', '2015', 'Python IDE', '1500')
insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('ECsjL', 'chhweon', 'Eclipse Foundation', 'www.eclipse.org', '2017', 'Eclipse IDE', '1700')

insert into predmet_softver(predmet_oznaka, softver_oznaka) values ('HCI', 'VS15')