insert into smer(oznaka, naziv, datum, opis) values ('siit', 'softversko inzenjerstvo i informacione tehnologije', '10.10.2014','opis smera' )
insert into predmet(oznaka, naziv, opis, smer_oznaka, velicina_grupe, duzina_termina, broj_termina, projektor, tabla, pametna_tabla, op_sistem  ) values ('HCI', 'Interakcija covek racunar', 'opis predmeta', 'siit', '15', '2', '4', true, true, false, 'WINDOWS' )
insert into predmet(oznaka, naziv, opis, smer_oznaka, velicina_grupe, duzina_termina, broj_termina, projektor, tabla, pametna_tabla, op_sistem  ) values ('Asc', 'Baze podataka', 'opis predmeta', 'siit', '15', '2', '4', true, true, false, 'WINDOWS' )
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L1', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L2', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L3', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L17', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L4', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L5', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L6', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L7', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L8', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L9', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L10', 'opis ucionice', '25', true, true, true, 'WINLINUX')
insert into ucionica(oznaka, opis, broj_mesta, projektor, tabla, pametna_tabla, op_sistem ) values ('L11', 'opis ucionice', '25', true, true, true, 'WINLINUX')


insert into softver(oznaka, naziv, proizvodjac, sajt, godina_izdavanja, opis, cena) values ('VS15', 'Visual studio', 'Microsoft', 'www.microsoft.com', '2015', 'opis proizvoda', '2000')